-- =========================================================
-- SCAMSHIELD DATABASE
-- Supabase / PostgreSQL Version
-- =========================================================

-- =========================================================
-- 1. CLEAN OLD TABLES
-- =========================================================

DROP TABLE IF EXISTS feedback_events CASCADE;
DROP TABLE IF EXISTS scan_explanations CASCADE;
DROP TABLE IF EXISTS scan_results CASCADE;
DROP TABLE IF EXISTS spam_domains CASCADE;
DROP TABLE IF EXISTS spam_numbers CASCADE;
DROP TABLE IF EXISTS scam_patterns CASCADE;
DROP TABLE IF EXISTS demo_cases CASCADE;
DROP TABLE IF EXISTS messages_log CASCADE;


-- =========================================================
-- 2. TABLE: messages_log
-- =========================================================

CREATE TABLE messages_log (
    scan_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    message VARCHAR(2000),
    phone_number VARCHAR(20),
    link VARCHAR(500),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT messages_log_pkey
        PRIMARY KEY (scan_id)
);


-- =========================================================
-- 3. TABLE: demo_cases
-- =========================================================

CREATE TABLE demo_cases (
    case_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(100) NOT NULL,
    sample_message VARCHAR(2000),
    sample_number VARCHAR(20),
    sample_link VARCHAR(500),
    expected_level VARCHAR(20),

    CONSTRAINT demo_cases_pkey
        PRIMARY KEY (case_id)
);


-- =========================================================
-- 4. TABLE: scam_patterns
-- =========================================================

CREATE TABLE scam_patterns (
    pattern_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    pattern_name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    keywords VARCHAR(500),
    risk_score INTEGER,

    CONSTRAINT scam_patterns_pkey
        PRIMARY KEY (pattern_id)
);


-- =========================================================
-- 5. TABLE: spam_numbers
-- =========================================================

CREATE TABLE spam_numbers (
    number_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    phone_number VARCHAR(20) NOT NULL,
    reputation VARCHAR(50),
    report_count INTEGER DEFAULT 0,

    CONSTRAINT spam_numbers_pkey
        PRIMARY KEY (number_id),

    CONSTRAINT unique_phone_number
        UNIQUE (phone_number)
);


-- =========================================================
-- 6. TABLE: spam_domains
-- =========================================================

CREATE TABLE spam_domains (
    domain_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    domain VARCHAR(255) NOT NULL,
    brand_misuse VARCHAR(100),
    reputation VARCHAR(50),

    CONSTRAINT spam_domains_pkey
        PRIMARY KEY (domain_id),

    CONSTRAINT unique_domain
        UNIQUE (domain)
);


-- =========================================================
-- 7. TABLE: scan_results
-- =========================================================

CREATE TABLE scan_results (
    result_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    scan_id INTEGER NOT NULL,

    final_score INTEGER,
    risk_level VARCHAR(20),
    recommendation VARCHAR(500),

    message_score INTEGER,
    number_score INTEGER,
    link_score INTEGER,

    CONSTRAINT scan_results_pkey
        PRIMARY KEY (result_id),

    CONSTRAINT scan_results_scan_id_fkey
        FOREIGN KEY (scan_id)
        REFERENCES messages_log(scan_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


-- =========================================================
-- 8. TABLE: scan_explanations
-- =========================================================

CREATE TABLE scan_explanations (
    explanation_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    scan_id INTEGER NOT NULL,

    fingerprint_json JSONB,
    attack_chain_json JSONB,
    confidence VARCHAR(20),
    what_if_json JSONB,

    CONSTRAINT scan_explanations_pkey
        PRIMARY KEY (explanation_id),

    CONSTRAINT scan_explanations_scan_id_fkey
        FOREIGN KEY (scan_id)
        REFERENCES messages_log(scan_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


-- =========================================================
-- 9. TABLE: feedback_events
-- =========================================================

CREATE TABLE feedback_events (
    feedback_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    scan_id INTEGER NOT NULL,

    verdict VARCHAR(50),
    note VARCHAR(500),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT feedback_events_pkey
        PRIMARY KEY (feedback_id),

    CONSTRAINT feedback_events_scan_id_fkey
        FOREIGN KEY (scan_id)
        REFERENCES messages_log(scan_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


-- =========================================================
-- 10. INSERT: demo_cases
-- =========================================================

INSERT INTO demo_cases
(
    case_id,
    title,
    sample_message,
    sample_number,
    sample_link,
    expected_level
)
OVERRIDING SYSTEM VALUE
VALUES
(
    1,
    'SBI KYC Phishing Alert',
    'Dear customer, your SBI account is suspended today. Update KYC immediately at http://secure-sbi-update-kyc.com',
    '+919876543210',
    'http://secure-sbi-update-kyc.com',
    'CRITICAL'
),
(
    2,
    'Telegram Crypto Scam',
    'You won 0.5 BTC! Claim your reward now at http://free-crypto-airdrop.xyz',
    '+919123456789',
    'http://free-crypto-airdrop.xyz',
    'HIGH'
),
(
    3,
    'Electricity Disconnection Scam',
    'Dear consumer your electricity line will be disconnected tonight at 9:30 PM. Call officer at +918888877777',
    '+918888877777',
    NULL,
    'CRITICAL'
),
(
    4,
    'YouTube Like Job Scam',
    'Earn Rs 5000/day by liking YouTube videos. Join our Telegram group now!',
    '+919999900000',
    'http://amazon-parttime-job.vip',
    'HIGH'
),
(
    5,
    'Fake Traffic E-Challan',
    'Traffic Challan pending against your vehicle. Clear fine before court notice: http://paytm-cashback-claim.org',
    '+917000011111',
    'http://paytm-cashback-claim.org',
    'MEDIUM'
);


-- =========================================================
-- 11. INSERT: messages_log
-- =========================================================

INSERT INTO messages_log
(
    scan_id,
    message,
    phone_number,
    link,
    created_at
)
OVERRIDING SYSTEM VALUE
VALUES
(
    1,
    'Dear customer, your SBI account is suspended today. Update KYC immediately at http://secure-sbi-update-kyc.com',
    '+919876543210',
    'http://secure-sbi-update-kyc.com',
    '2026-08-20 13:01:17+05:30'
),
(
    2,
    'You won 0.5 BTC! Claim your reward now at http://free-crypto-airdrop.xyz',
    '+919123456789',
    'http://free-crypto-airdrop.xyz',
    '2026-08-20 13:01:17+05:30'
),
(
    3,
    'Dear consumer your electricity line will be disconnected tonight at 9:30 PM. Call officer at +918888877777',
    '+918888877777',
    NULL,
    '2026-08-20 13:01:17+05:30'
),
(
    4,
    'Earn Rs 5000/day by liking YouTube videos. Join our Telegram group now!',
    '+919999900000',
    'http://amazon-parttime-job.vip',
    '2026-08-20 13:01:17+05:30'
),
(
    5,
    'Traffic Challan pending against your vehicle. Clear fine before court notice: http://paytm-cashback-claim.org',
    '+917000011111',
    'http://paytm-cashback-claim.org',
    '2026-08-20 13:01:17+05:30'
);


-- =========================================================
-- 12. INSERT: scam_patterns
-- =========================================================

INSERT INTO scam_patterns
(
    pattern_id,
    pattern_name,
    description,
    keywords,
    risk_score
)
OVERRIDING SYSTEM VALUE
VALUES
(
    1,
    'Banking Urgency Scam',
    'Urgent request to verify bank account or KYC to avoid suspension.',
    'KYC, block, expired, urgent, verify',
    90
),
(
    2,
    'Lottery Fraud',
    'Fake claims of winning cash prize requiring processing fee.',
    'congratulations, won, claim, cash, transfer',
    85
),
(
    3,
    'Part-Time Job Scam',
    'Promises easy daily income via YouTube likes or Telegram tasks.',
    'part-time, earn daily, telegram, task, pre-pay',
    88
),
(
    4,
    'Electricity Bill Threat',
    'Threatens to disconnect power supply tonight if bill is not paid via link.',
    'electricity, power cut, bill due, tonight, light officer',
    95
),
(
    5,
    'E-Challan Fake Alert',
    'Fake traffic violation notice forcing payment on scam URL.',
    'challan, traffic police, pending fine, pay immediately',
    82
);


-- =========================================================
-- 13. INSERT: spam_numbers
-- =========================================================

INSERT INTO spam_numbers
(
    number_id,
    phone_number,
    reputation,
    report_count
)
OVERRIDING SYSTEM VALUE
VALUES
(
    1,
    '+919876543210',
    'HIGH_RISK',
    142
),
(
    2,
    '+919123456789',
    'SUSPICIOUS',
    28
),
(
    3,
    '+918888877777',
    'HIGH_RISK',
    210
),
(
    4,
    '+917000011111',
    'SAFE',
    0
),
(
    5,
    '+919999900000',
    'HIGH_RISK',
    89
);


-- =========================================================
-- 14. INSERT: spam_domains
-- =========================================================

INSERT INTO spam_domains
(
    domain_id,
    domain,
    brand_misuse,
    reputation
)
OVERRIDING SYSTEM VALUE
VALUES
(
    1,
    'secure-sbi-update-kyc.com',
    'SBI Bank',
    'MALICIOUS'
),
(
    2,
    'free-crypto-airdrop.xyz',
    'Binance',
    'PHISHING'
),
(
    3,
    'hdfc-rewards-login.net',
    'HDFC Bank',
    'MALICIOUS'
),
(
    4,
    'paytm-cashback-claim.org',
    'Paytm',
    'SUSPICIOUS'
),
(
    5,
    'amazon-parttime-job.vip',
    'Amazon',
    'MALICIOUS'
);


-- =========================================================
-- 15. INSERT: scan_results
-- =========================================================

INSERT INTO scan_results
(
    result_id,
    scan_id,
    final_score,
    risk_level,
    recommendation,
    message_score,
    number_score,
    link_score
)
OVERRIDING SYSTEM VALUE
VALUES
(
    1,
    1,
    92,
    'CRITICAL',
    'Do not click the link. Block sender immediately and report on cybercrime portal.',
    88,
    95,
    93
),
(
    2,
    2,
    84,
    'HIGH',
    'Potentially fraudulent giveaway. Do not connect your crypto wallet.',
    80,
    80,
    92
),
(
    3,
    3,
    96,
    'CRITICAL',
    'Impersonation scam. Do not call the provided contact number.',
    95,
    98,
    0
),
(
    4,
    4,
    88,
    'HIGH',
    'Task-based financial fraud scheme detected.',
    85,
    89,
    90
),
(
    5,
    5,
    75,
    'MEDIUM',
    'Suspicious URL posing as official payment gateway.',
    70,
    20,
    85
);


-- =========================================================
-- 16. INSERT: scan_explanations
-- =========================================================

INSERT INTO scan_explanations
(
    explanation_id,
    scan_id,
    fingerprint_json,
    attack_chain_json,
    confidence,
    what_if_json
)
OVERRIDING SYSTEM VALUE
VALUES
(
    1,
    1,
    '{"type":"Phishing","brand":"SBI"}',
    '{"step1":"SMS received","step2":"Link redirects to fake login"}',
    '98%',
    '{"if_clicked":"Bank credentials compromised"}'
),
(
    2,
    2,
    '{"type":"Crypto Fraud","brand":"Binance"}',
    '{"step1":"Unsolicited reward","step2":"Malicious smart contract call"}',
    '91%',
    '{"if_clicked":"Wallet drained"}'
),
(
    3,
    3,
    '{"type":"Impersonation","brand":"State Electricity Board"}',
    '{"step1":"Threat SMS","step2":"Coerced direct call/transfer"}',
    '99%',
    '{"if_called":"Social engineering pressure for quick payment"}'
),
(
    4,
    4,
    '{"type":"Employment Scam","brand":"Amazon/YouTube"}',
    '{"step1":"Task lure","step2":"Telegram onboarding","step3":"Prepayment demand"}',
    '94%',
    '{"if_joined":"Advanced fee scam loss"}'
),
(
    5,
    5,
    '{"type":"Smishing","brand":"Traffic Police"}',
    '{"step1":"Fake fine SMS","step2":"Phishing gateway"}',
    '89%',
    '{"if_clicked":"Payment gateway credential harvesting"}'
);


-- =========================================================
-- 17. INSERT: feedback_events
-- =========================================================

INSERT INTO feedback_events
(
    feedback_id,
    scan_id,
    verdict,
    note,
    created_at
)
OVERRIDING SYSTEM VALUE
VALUES
(
    1,
    1,
    'CONFIRMED_SCAM',
    'Verified phishing URL mimicking official SBI domain',
    '2026-08-20 13:01:17+05:30'
),
(
    2,
    2,
    'CONFIRMED_SCAM',
    'Reported by community users as wallet drainer',
    '2026-08-20 13:01:17+05:30'
),
(
    3,
    3,
    'CONFIRMED_SCAM',
    'Known electricity bill scam pattern active nationwide',
    '2026-08-20 13:01:17+05:30'
),
(
    4,
    4,
    'CONFIRMED_SCAM',
    'Telegram task scam reported multiple times',
    '2026-08-20 13:01:17+05:30'
),
(
    5,
    5,
    'SUSPICIOUS',
    'Pending manual verification by domain scanner',
    '2026-08-20 13:01:17+05:30'
);


-- =========================================================
-- 18. RESET IDENTITY SEQUENCES
-- =========================================================

SELECT setval(
    pg_get_serial_sequence('demo_cases', 'case_id'),
    COALESCE((SELECT MAX(case_id) FROM demo_cases), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('messages_log', 'scan_id'),
    COALESCE((SELECT MAX(scan_id) FROM messages_log), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('scam_patterns', 'pattern_id'),
    COALESCE((SELECT MAX(pattern_id) FROM scam_patterns), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('spam_numbers', 'number_id'),
    COALESCE((SELECT MAX(number_id) FROM spam_numbers), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('spam_domains', 'domain_id'),
    COALESCE((SELECT MAX(domain_id) FROM spam_domains), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('scan_results', 'result_id'),
    COALESCE((SELECT MAX(result_id) FROM scan_results), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('scan_explanations', 'explanation_id'),
    COALESCE((SELECT MAX(explanation_id) FROM scan_explanations), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('feedback_events', 'feedback_id'),
    COALESCE((SELECT MAX(feedback_id) FROM feedback_events), 1),
    true
);


-- =========================================================
-- 19. VERIFY TABLES
-- =========================================================

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
AND table_name IN (
    'demo_cases',
    'feedback_events',
    'messages_log',
    'scam_patterns',
    'scan_explanations',
    'scan_results',
    'spam_domains',
    'spam_numbers'
)
ORDER BY table_name;


-- =========================================================
-- 20. VERIFY DATA
-- =========================================================

SELECT COUNT(*) AS demo_cases_count
FROM demo_cases;

SELECT COUNT(*) AS messages_count
FROM messages_log;

SELECT COUNT(*) AS patterns_count
FROM scam_patterns;

SELECT COUNT(*) AS numbers_count
FROM spam_numbers;

SELECT COUNT(*) AS domains_count
FROM spam_domains;

SELECT COUNT(*) AS results_count
FROM scan_results;

SELECT COUNT(*) AS explanations_count
FROM scan_explanations;

SELECT COUNT(*) AS feedback_count
FROM feedback_events;