-- =========================================================
-- SCAMSHIELD - INITIAL DATABASE SCHEMA
-- PostgreSQL / Supabase
-- =========================================================

-- =========================================================
-- 1. MESSAGES LOG
-- =========================================================

CREATE TABLE IF NOT EXISTS messages_log (
    scan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message VARCHAR(2000),
    phone_number VARCHAR(20),
    link VARCHAR(500),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 2. DEMO CASES
-- =========================================================

CREATE TABLE IF NOT EXISTS demo_cases (
    case_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    sample_message VARCHAR(2000),
    sample_number VARCHAR(20),
    sample_link VARCHAR(500),
    expected_level VARCHAR(20)
);


-- =========================================================
-- 3. SCAM PATTERNS
-- =========================================================

CREATE TABLE IF NOT EXISTS scam_patterns (
    pattern_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern_name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    keywords VARCHAR(500),
    risk_score INTEGER
);


-- =========================================================
-- 4. SPAM NUMBERS
-- =========================================================

CREATE TABLE IF NOT EXISTS spam_numbers (
    number_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(20) NOT NULL UNIQUE,
    reputation VARCHAR(50),
    report_count INTEGER DEFAULT 0
);


-- =========================================================
-- 5. SPAM DOMAINS
-- =========================================================

CREATE TABLE IF NOT EXISTS spam_domains (
    domain_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain VARCHAR(255) NOT NULL UNIQUE,
    brand_misuse VARCHAR(100),
    reputation VARCHAR(50)
);


-- =========================================================
-- 6. SCAN RESULTS
-- =========================================================

CREATE TABLE IF NOT EXISTS scan_results (
    result_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id INTEGER NOT NULL,

    final_score INTEGER,
    risk_level VARCHAR(20),
    recommendation VARCHAR(500),

    message_score INTEGER,
    number_score INTEGER,
    link_score INTEGER,

    CONSTRAINT scan_results_scan_id_fkey
        FOREIGN KEY (scan_id)
        REFERENCES messages_log(scan_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


-- =========================================================
-- 7. SCAN EXPLANATIONS
-- =========================================================

CREATE TABLE IF NOT EXISTS scan_explanations (
    explanation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id INTEGER NOT NULL,

    fingerprint_json JSONB,
    attack_chain_json JSONB,
    confidence VARCHAR(20),
    what_if_json JSONB,

    CONSTRAINT scan_explanations_scan_id_fkey
        FOREIGN KEY (scan_id)
        REFERENCES messages_log(scan_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


-- =========================================================
-- 8. FEEDBACK EVENTS
-- =========================================================

CREATE TABLE IF NOT EXISTS feedback_events (
    feedback_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id INTEGER NOT NULL,

    verdict VARCHAR(50),
    note VARCHAR(500),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT feedback_events_scan_id_fkey
        FOREIGN KEY (scan_id)
        REFERENCES messages_log(scan_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


-- =========================================================
-- 9. INDEXES
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_scan_results_scan_id
ON scan_results(scan_id);

CREATE INDEX IF NOT EXISTS idx_scan_explanations_scan_id
ON scan_explanations(scan_id);

CREATE INDEX IF NOT EXISTS idx_feedback_scan_id
ON feedback_events(scan_id);

CREATE INDEX IF NOT EXISTS idx_messages_phone_number
ON messages_log(phone_number);

CREATE INDEX IF NOT EXISTS idx_messages_created_at
ON messages_log(created_at);


-- =========================================================
-- 10. DEMO DATA
-- =========================================================

INSERT INTO demo_cases
(title, sample_message, sample_number, sample_link, expected_level)
VALUES
(
    'SBI KYC Phishing Alert',
    'Dear customer, your SBI account is suspended today. Update KYC immediately at http://secure-sbi-update-kyc.com',
    '+919876543210',
    'http://secure-sbi-update-kyc.com',
    'CRITICAL'
),
(
    'Telegram Crypto Scam',
    'You won 0.5 BTC! Claim your reward now at http://free-crypto-airdrop.xyz',
    '+919123456789',
    'http://free-crypto-airdrop.xyz',
    'HIGH'
),
(
    'Electricity Disconnection Scam',
    'Dear consumer your electricity line will be disconnected tonight at 9:30 PM. Call officer at +918888877777',
    '+918888877777',
    NULL,
    'CRITICAL'
),
(
    'YouTube Like Job Scam',
    'Earn Rs 5000/day by liking YouTube videos. Join our Telegram group now!',
    '+919999900000',
    'http://amazon-parttime-job.vip',
    'HIGH'
),
(
    'Fake Traffic E-Challan',
    'Traffic Challan pending against your vehicle. Clear fine before court notice: http://paytm-cashback-claim.org',
    '+917000011111',
    'http://paytm-cashback-claim.org',
    'MEDIUM'
);


-- =========================================================
-- 11. SCAM PATTERNS DATA
-- =========================================================

INSERT INTO scam_patterns
(pattern_name, description, keywords, risk_score)
VALUES
(
    'Banking Urgency Scam',
    'Urgent request to verify bank account or KYC to avoid suspension.',
    'KYC, block, expired, urgent, verify',
    90
),
(
    'Lottery Fraud',
    'Fake claims of winning cash prize requiring processing fee.',
    'congratulations, won, claim, cash, transfer',
    85
),
(
    'Part-Time Job Scam',
    'Promises easy daily income via YouTube likes or Telegram tasks.',
    'part-time, earn daily, telegram, task, pre-pay',
    88
),
(
    'Electricity Bill Threat',
    'Threatens to disconnect power supply tonight if bill is not paid via link.',
    'electricity, power cut, bill due, tonight, light officer',
    95
),
(
    'E-Challan Fake Alert',
    'Fake traffic violation notice forcing payment on scam URL.',
    'challan, traffic police, pending fine, pay immediately',
    82
);


-- =========================================================
-- 12. SPAM NUMBERS
-- =========================================================

INSERT INTO spam_numbers
(phone_number, reputation, report_count)
VALUES
('+919876543210', 'HIGH_RISK', 142),
('+919123456789', 'SUSPICIOUS', 28),
('+918888877777', 'HIGH_RISK', 210),
('+917000011111', 'SAFE', 0),
('+919999900000', 'HIGH_RISK', 89);


-- =========================================================
-- 13. SPAM DOMAINS
-- =========================================================

INSERT INTO spam_domains
(domain, brand_misuse, reputation)
VALUES
(
    'secure-sbi-update-kyc.com',
    'SBI Bank',
    'MALICIOUS'
),
(
    'free-crypto-airdrop.xyz',
    'Binance',
    'PHISHING'
),
(
    'hdfc-rewards-login.net',
    'HDFC Bank',
    'MALICIOUS'
),
(
    'paytm-cashback-claim.org',
    'Paytm',
    'SUSPICIOUS'
),
(
    'amazon-parttime-job.vip',
    'Amazon',
    'MALICIOUS'
);